apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ofek18100/naturewallfrontend:0.4
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 900Mi
            cpu: 2
          requests:
            cpu: 500m
            memory: 700Mi

        env:
          - name: ENV
            value: "CIVO2"
