apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: naturewall
spec:
  rules:
    - host: 
      http:
        paths:
        - path: /
          pathType: Exact
          backend:
            service:
              name: frontend
              port:
                number: 80
